title: where there is no doctor
email:
description: Village Healthcare Handbook is the most widely-used health care manual for health workers, educators and others, involved in primary health care and health promotion around the world. Current edition includes updated information on malaria, HIV, and more.
baseurl: "/wherenodoctor"
url: "https://junglesta.github.io"
twitter_username: rokmatwit
github:
  repository: junglesta/wherenodoctor
producer:
  name: Jungle★star
  url: http://junglestar.org

# Build settings
markdown: kramdown
release: 0.3.0
permalink: nil ## should disable post output, but...
exclude: [gulpfile.js, node_modules, package.json, icon, Gemfile, Gemfile.lock, LICENSE]


#turn off if something is not working:
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6]
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
