title: Where There Is No Doctor
email:
description: Village Healthcare Handbook is the most widely-used health care manual for health workers, educators and others, involved in primary health care and health promotion around the world. Current edition includes updated information on malaria, HIV, and more. This is an offline-ready book. On Android select add-to-your-home-screen and you're ready to use the whole book while offline too.
baseurl: ""
url: "https://nodoctor.junglestar.org"

twitter_username: rokmatwit
repository: junglesta/wherenodoctor
repository_url: https://github.com/junglesta/wherenodoctor
producer:
  name: Jungle★star
  url: https://junglestar.org

# Build settings
markdown: kramdown
release: 0.4.1
permalink: nil ## should disable post output, but...
exclude: [gulpfile.js, node_modules, package.json, icon, Gemfile, Gemfile.lock, LICENSE]

#this version of jekyll need plugins_dir here:
plugins_dir:
  - html-proofer
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

#turn off if something is not working:
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6]
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
