title: where there is no doctor
email:
description: Village Healthcare Handbook is the most widely-used health care manual for health workers, educators, and others involved in primary health care and health promotion around the world. Current edition includes updated information on malaria, HIV, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rokmatwit
github_username:  toybreaker
producer:
  name: Junglestar
  url: http://junglestar.org

# Build settings
markdown: kramdown
